//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GE.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME_PMWIN             103
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_UNCHECK              131
#define IDB_BITMAP_CHECK                132
#define IDD_SCALE                       146
#define IDD_VISUALIZE                   147
#define IDR_ADD                         154
#define IDD_GEOSPATIAL_MODEL_GENERAL    164
#define IDD_GEOSPATIAL_MODEL_VISIBLE    166
#define IDD_GEOSPATIAL_MODEL_AVERAGE    167
#define IDD_XYZ_SURFACE_GENERAL         170
#define IDD_XYZ_SURFACE_DECSMOOTH       171
#define IDD_HYDRAULIC_COMPONENTS_GENERAL 173
#define IDD_POTENTIOMETRIC_SURFACE_GENERAL 177
#define IDD_POTENTIOMETRIC_SURFACE_AVERAGE 181
#define IDD_POTENTIOMETRIC_SURFACE_CONTOURS 182
#define IDD_COLOR_PAGE                  183
#define IDD_PARAMETER_AVERAGE           186
#define IDD_PARAMETER_GENERAL           187
#define IDD_MT3DMS_GENERAL              191
#define IDD_MT3DMS_CONTOUR_COLOR        194
#define IDD_COLOR_SPECTRUM              195
#define IDD_COLOR_LEVEL                 196
#define IDD_CLIP                        198
#define IDD_HYDRAULIC_COMPONENTS_AVERAGE 208
#define IDI_ICON_CHECK                  211
#define IDI_ICON_UNCHECK                212
#define IDD_AXES                        213
#define IDD_MT3DMS_ADD_CONTOUR_COLOR    215
#define IDB_BITMAP_SELECT               216
#define IDB_BITMAP_UNSELECT             217
#define IDD_MODEL_OUTLINE_GENERAL       220
#define IDD_HYDRAULIC_COMPONENTS_GENERAL_TD 231
#define IDC_MSFLEXGRID                  1034
#define IDC_EDIT_XSCALE                 1035
#define IDC_EDIT_YSCALE                 1036
#define IDC_EDIT_ZSCALE                 1037
#define IDC_COMBO_STRESS_PERIOD         1042
#define IDC_CHECK_AVERAGE               1043
#define IDC_COMBO_TIME_STEP             1043
#define IDC_CHECK_X                     1043
#define IDC_CHECK_DECIMATE              1044
#define IDC_EDIT_XNORMAL                1044
#define IDC_COMBO_LAYER                 1044
#define IDC_CHECK_Y                     1044
#define IDC_CHECK_SMOOTH                1045
#define IDC_EDIT_YNORMAL                1045
#define IDC_CHECK_Z                     1045
#define IDC_EDIT_ZNORMAL                1046
#define IDC_CHECK_X2                    1046
#define IDC_BUTTON_ADD                  1055
#define IDC_BUTTON_REMOVE               1056
#define IDC_EDIT_OPACITY                1057
#define IDC_EDIT_FONT_FACTOR            1057
#define IDC_EDIT_X_MINIMUM              1057
#define IDC_EDIT_ITERATIONS             1058
#define IDC_EDIT_NUMBER_OF_LABELS       1058
#define IDC_EDIT_X_MAXIMUM              1058
#define IDC_EDIT_RELAXATION             1059
#define IDC_SPECIES_NUMBER              1059
#define IDC_BUTTON_MINIMUM_COLOR        1059
#define IDC_EDIT_Y_MINIMUM              1059
#define IDC_EDIT_MAXIMUM                1060
#define IDC_TOTAL_ELAPSED_TIME          1060
#define IDC_EDIT_Y_MAXIMUM              1060
#define IDC_EDIT_Z_MINIMUM              1061
#define IDC_EDIT_Z_MAXIMUM              1062
#define IDC_CHECK_CLIP                  1069
#define IDC_EDIT_DESCRIPTION            1072
#define IDC_EDIT_PATHNAME               1073
#define IDC_MSFLEXGRID_VISIBLE          1079
#define IDC_VISUALIZEGRID               1080
#define IDC_BUTTON_OPEN_XYZFILE         1081
#define IDC_CHECK_VISIBLE               1086
#define IDC_EDIT_MINIMUM                1087
#define IDC_EDIT_INTERVAL               1088
#define IDC_EDIT_REDUCTION              1089
#define IDC_STATIC_MINIMUM_COLOR        1091
#define IDC_STATIC_MAXIMUM_COLOR        1097
#define IDC_BUTTON_MAXIMUM_COLOR        1098
#define IDC_EDIT_XORIGIN                1099
#define IDC_EDIT_YORIGIN                1100
#define IDC_EDIT_ZORIGIN                1101
#define IDC_CHECK_HIGHEST_HEADS         1103
#define IDC_STATIC_COLOR                1104
#define IDC_BUTTON_COLOR                1105
#define IDC_EDIT_VALUE                  1106
#define IDC_SLD_OPACITY                 1111
#define IDC_SLD_Y_NORMAL                1112
#define IDC_SLD_Z_NORMAL                1113
#define IDC_SLD_X_NORMAL                1114
#define ID_INTERACT_SCALE               32795
#define ID_FILE_IMPORT_PMWINMODEL       32804
#define ID_OPTIONS_VISUALIZE            32818
#define ID_ADD_XYZSURFACE               32821
#define ID_ADD_GEOSPATIAL_MODEL         32822
#define ID_EDIT_CREATEVRML              32823
#define ID_ADD_POTENTIOMETRIC_SURFACE   32825
#define ID_ADD_ISOSURFACE_MT3DMS        32834
#define ID_ADD_PARAMETER_HORIZONTAL_HYDRAULIC_CONDUCTIVITY 32837
#define ID_ADD_PARAMETER_VERTICAL_HYDRAULIC_CONDUCTIVITY 32838
#define ID_ADD_PARAMETER_SPECIFIC_STORAGE 32839
#define ID_ADD_PARAMETER_TRANSMISSIVITY 32840
#define ID_ADD_PARAMETER_VERTICAL_LEAKANCE 32841
#define ID_ADD_PARAMETER_STORAGE_COEFFICIENT 32842
#define ID_ADD_PARAMETER_EFFECTIVE_POROSITY 32843
#define ID_ADD_PARAMETER_SPECIFIC_YIELD 32844
#define ID_INTERACT_CLIP                32856
#define ID_BUTTON_VISUALIZE             32861
#define ID_OPTIONS_AXES                 32866
#define ID_ADD_MODEL_OUTLINE            32867
#define ID_ADD_HYDRAULICCOMPONENTS_TIMEINDEPENDANT 32870
#define ID_ADD_HYDRAULICCOMPONENTS_TIMEDEPENDENT 32871
#define ID_ADD_ISOSURFACE_PHT3D         32873
#define ID_ADD_ISOSURFACE_RT3D          32874
#define AFX_IDS_CONTOURING              57346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        234
#define _APS_NEXT_COMMAND_VALUE         32875
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
